---
- name: "Prepare"
  become: true
  raw: mkdir -p /var/lib/backend/

- name: "Check"
  become: true
  shell: "env"
  register: env_info

- name: "Unpack"
  become: true
  unarchive:
    src: "artifact.tar.gz"
    dest: /var/lib/backend

- name: "start pm2"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: /var/lib/backend
  register: run_info
  
- debug:
    msg: "{{run_info.stdout_lines}}"