---
- name: "Prepare"
  become: true
  raw: mkdir -p /var/lib/backend/

- name: "Unpack"
  become: true
  unarchive:
    src: "artifact.tar.gz"
    dest: /var/lib/backend

- name: "Check env"
  become: true
  raw: env

- name: "start pm2"
  become: true
  raw: cd /var/lib/backend && npm install && pm2 stop default && pm2 start npm -- start